import { ThemeColors } from '../types/reader';

export const ACCENT_PALETTE = [
  { name: 'Crimson Neon', value: '#ff4757' },
  { name: 'Sunset Coral', value: '#ff6b6b' },
  { name: 'Amber Gold', value: '#f59e0b' },
  { name: 'Emerald Mint', value: '#10b981' },
  { name: 'Electric Cyan', value: '#06b6d4' },
  { name: 'Cobalt Blue', value: '#3b82f6' },
  { name: 'Vibrant Violet', value: '#8b5cf6' },
  { name: 'Hot Magenta', value: '#ec4899' },
  { name: 'Optic White', value: '#ffffff' },
];

export const THEMES: Record<string, ThemeColors> = {
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Void Obsidian (Default)',
    bg: '#0a0d13',
    surface: '#121620',
    surfaceHover: '#181e2b',
    border: '#1f2738',
    textBright: '#f1f5f9',
    textDim: '#8592a6',
    accent: '#ff4757',
    isDark: true,
  },
  oled: {
    id: 'oled',
    name: 'OLED Pure Black',
    bg: '#000000',
    surface: '#0b0b0d',
    surfaceHover: '#141417',
    border: '#1e1e24',
    textBright: '#ffffff',
    textDim: '#71717a',
    accent: '#ff3344',
    isDark: true,
  },
  sepia: {
    id: 'sepia',
    name: 'Warm Parchment (Book)',
    bg: '#fbf0d9',
    surface: '#f3e5c8',
    surfaceHover: '#ebe0bb',
    border: '#dcd1b3',
    textBright: '#291e13',
    textDim: '#6b5847',
    accent: '#b91c1c',
    isDark: false,
  },
  solarizedDark: {
    id: 'solarizedDark',
    name: 'Solarized Dark',
    bg: '#002b36',
    surface: '#073642',
    surfaceHover: '#0a4250',
    border: '#0d4a58',
    textBright: '#eee8d5',
    textDim: '#839496',
    accent: '#268bd2',
    isDark: true,
  },
  solarizedLight: {
    id: 'solarizedLight',
    name: 'Solarized Cream',
    bg: '#fdf6e3',
    surface: '#eee8d5',
    surfaceHover: '#e4dcc7',
    border: '#d3c9b0',
    textBright: '#073642',
    textDim: '#657b83',
    accent: '#cb4b16',
    isDark: false,
  },
  nordic: {
    id: 'nordic',
    name: 'Nordic Frost',
    bg: '#181b22',
    surface: '#20242e',
    surfaceHover: '#282e3b',
    border: '#2e3544',
    textBright: '#e6edf3',
    textDim: '#8b949e',
    accent: '#58a6ff',
    isDark: true,
  },
  emerald: {
    id: 'emerald',
    name: 'Midnight Emerald',
    bg: '#08120e',
    surface: '#0f2019',
    surfaceHover: '#152b22',
    border: '#1a3b2e',
    textBright: '#ecfdf5',
    textDim: '#6ee7b7',
    accent: '#10b981',
    isDark: true,
  },
  paper: {
    id: 'paper',
    name: 'Clean Studio White',
    bg: '#ffffff',
    surface: '#f4f4f5',
    surfaceHover: '#e4e4e7',
    border: '#e4e4e7',
    textBright: '#09090b',
    textDim: '#52525b',
    accent: '#e11d48',
    isDark: false,
  },
};
